# Generated by Django 4.1 on 2022-09-04 23:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('username', models.OneToOneField(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Massage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('massage_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('address', models.TextField()),
                ('address_url', models.TextField()),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration', models.TimeField(choices=[(datetime.time(1, 0), '60 minutes'), (datetime.time(1, 15), '75 minutes'), (datetime.time(1, 30), '90 minutes')])),
                ('note', models.TextField(blank=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservation', to='api.customer')),
                ('massage_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Reservation', to='api.massage')),
            ],
        ),
        migrations.CreateModel(
            name='ManageReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateField(unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Manage_Reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
