# Generated by Django 4.0.6 on 2022-07-25 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='surmane',
            new_name='surname',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='duration',
            field=models.TimeField(choices=[(datetime.time(1, 0), '60 minutes'), (datetime.time(1, 15), '75 minutes'), (datetime.time(1, 30), '90 minutes')]),
        ),
    ]
