# Generated by Django 4.1 on 2022-08-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='course_minutes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
